//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapServiceTest2.MensajesWs2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MensajesWs2.IMensajes")]
    public interface IMensajes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Saludar", ReplyAction="http://tempuri.org/IMensajes/SaludarResponse")]
        string Saludar(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Saludar", ReplyAction="http://tempuri.org/IMensajes/SaludarResponse")]
        System.Threading.Tasks.Task<string> SaludarAsync(string nombre);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Despedir", ReplyAction="http://tempuri.org/IMensajes/DespedirResponse")]
        string Despedir(string nombre, string curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Despedir", ReplyAction="http://tempuri.org/IMensajes/DespedirResponse")]
        System.Threading.Tasks.Task<string> DespedirAsync(string nombre, string curso);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Descolor", ReplyAction="http://tempuri.org/IMensajes/DescolorResponse")]
        string Descolor(string nombrecolor);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/Descolor", ReplyAction="http://tempuri.org/IMensajes/DescolorResponse")]
        System.Threading.Tasks.Task<string> DescolorAsync(string nombrecolor);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensajesChannel : SoapServiceTest2.MensajesWs2.IMensajes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensajesClient : System.ServiceModel.ClientBase<SoapServiceTest2.MensajesWs2.IMensajes>, SoapServiceTest2.MensajesWs2.IMensajes {
        
        public MensajesClient() {
        }
        
        public MensajesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MensajesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Saludar(string nombre) {
            return base.Channel.Saludar(nombre);
        }
        
        public System.Threading.Tasks.Task<string> SaludarAsync(string nombre) {
            return base.Channel.SaludarAsync(nombre);
        }
        
        public string Despedir(string nombre, string curso) {
            return base.Channel.Despedir(nombre, curso);
        }
        
        public System.Threading.Tasks.Task<string> DespedirAsync(string nombre, string curso) {
            return base.Channel.DespedirAsync(nombre, curso);
        }
        
        public string Descolor(string nombrecolor) {
            return base.Channel.Descolor(nombrecolor);
        }
        
        public System.Threading.Tasks.Task<string> DescolorAsync(string nombrecolor) {
            return base.Channel.DescolorAsync(nombrecolor);
        }
    }
}
