//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoapServiceTest.MensajesWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MensajesWS.IMensajes")]
    public interface IMensajes {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/CadenaConexion", ReplyAction="http://tempuri.org/IMensajes/CadenaConexionResponse")]
        string CadenaConexion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/ObtenerTrainigProgram", ReplyAction="http://tempuri.org/IMensajes/ObtenerTrainigProgramResponse")]
        string ObtenerTrainigProgram(int trainig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/CalificarTrainigProgram", ReplyAction="http://tempuri.org/IMensajes/CalificarTrainigProgramResponse")]
        string CalificarTrainigProgram(int trainig);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/UPDCalificarTProgram", ReplyAction="http://tempuri.org/IMensajes/UPDCalificarTProgramResponse")]
        string UPDCalificarTProgram(int trainig, double score);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMensajes/EmailCalificarTProgram", ReplyAction="http://tempuri.org/IMensajes/EmailCalificarTProgramResponse")]
        string EmailCalificarTProgram(string msgto, string msgsubjet, string msgbody);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMensajesChannel : SoapServiceTest.MensajesWS.IMensajes, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MensajesClient : System.ServiceModel.ClientBase<SoapServiceTest.MensajesWS.IMensajes>, SoapServiceTest.MensajesWS.IMensajes {
        
        public MensajesClient() {
        }
        
        public MensajesClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MensajesClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MensajesClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CadenaConexion() {
            return base.Channel.CadenaConexion();
        }
        
        public string ObtenerTrainigProgram(int trainig) {
            return base.Channel.ObtenerTrainigProgram(trainig);
        }
        
        public string CalificarTrainigProgram(int trainig) {
            return base.Channel.CalificarTrainigProgram(trainig);
        }
        
        public string UPDCalificarTProgram(int trainig, double score) {
            return base.Channel.UPDCalificarTProgram(trainig, score);
        }
        
        public string EmailCalificarTProgram(string msgto, string msgsubjet, string msgbody) {
            return base.Channel.EmailCalificarTProgram(msgto, msgsubjet, msgbody);
        }
    }
}
